version: '3.8'

services:
  # 1. Container Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: certimatch_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: certimatch123
      POSTGRES_DB: certimatch_db
    ports:
      - "5432:5432" # Membuka port jika Anda butuh akses db via DBeaver/PGAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Container Frontend Next.js
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: certimatch_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:certimatch123@db:5432/certimatch_db?schema=public
      - PYTHON_API_URL=http://api:8000
    depends_on:
      - db
      - api

  # 3. Container Backend Python (Uvicorn)
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: certimatch_api
    restart: always
    ports:
      - "8000:8000" 

  # 4. Container Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: certimatch_tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    depends_on:
      - web

volumes:
  postgres_data:
